default: &default
  max_size: 1024

development:
  <<: *default
  local:
    path: ':rails_root/public/system/:class/:attachment/:id_partition/:style/:filename'
production:
  <<: *default
  s3:
    s3_credentials:
      access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
    bucket: <%= ENV['S3_ATTACHMENT_BUCKET'] %>
    s3_region: <%= ENV['S3_REGION'] || 'us-east-1' %>
    path: ':class/:attachment/:id_partition/:style/:filename'
